### ISSUE TITLE
Braintree Examples ?

### ISSUE THREAD

**Issue by daslicht** [OFFLINE-GmbH/oc-cashier-plugin#1]
Are tehre anywhere Braintree examples please?

**Comment by tobias-kuendig** [comment]
There are currently no braintree examples for this plugin since I have never use Braintree and am not planning to do so in the near future.

All this plugin does is integrate the Laravel Cashier plugin into October. You should be able to use the plugin exactly as described in the official Laravel docs: https://laravel.com/docs/5.5/billing#braintree-configuration
